---
# AWS Credentials
myaccess: "AKIAIRS74VVHSBZXISDA"
mysecret: "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"
myregion: "us-west-2"

#VPC Information
myvpc: "Test_VPC"
mycidr: "10.0.0.0/16"

# Subnets

mypubsubcidr1: "10.0.1.0/24"
mypubsubcidr2: "10.0.2.0/24"

myprisubcidr1: "10.0.3.0/24"
myprisubcidr2: "10.0.4.0/24"

#Defcidr

defcidr: "172.31.0.0/16"

#Key

mykey: "key"
myinst: "t2.micro"
myamid: "ami-f2d3638a"
mysec: "Test_SecGrp"

